In [3]:
num1=int (input("take first no"))
num2=int(input("take second no"))
total=num1+num2
print(total)

take first no


ValueError: invalid literal for int() with base 10: ''

In [4]:
num1=int(input("give your first digit:"))
num2=int(input("give your last digit :"))
print("the sum of first and last digit is"+(str(num1+num2))) 

give your first digit:


ValueError: invalid literal for int() with base 10: ''

In [5]:
print("raza","dsl","fb",)

raza dsl fb


In [6]:
print("raza","dsl","fb",sep="========")

raza========dsl========fb


In [7]:
print("younus",end=" ")
print("raza")

younus raza


In [8]:
print("younus",end=" ")
print("raza")

younus raza


In [9]:
print("younus",end="\t")
print("raza")

younus	raza


In [10]:
print("younus","raza",sep="iamseparator",end=" ")


younusiamseparatorraza 

In [11]:
num1=int(input("your marks in maths sub:"))
num2=int(input("your marks in english sub:"))
total=print("avg marks in both sub are:"+" "+(str(num1+num2)))

your marks in maths sub:


ValueError: invalid literal for int() with base 10: ''

In [12]:
a=10 #assign a value 10 to a variable a
b=20
a==b #compare the value of a with b 

False

In [13]:
a=10 #assign a value 10 to a variable a
b=20/2
a==b #compare the value of a with b 

True

In [14]:
a=10 #assign a value 10 to a variable a
b=20/2
a==b #compare the value of a with b 
tomatoprice=100
if tomatoprice==100:
    print("buy 1 kg")#indentation
else:
    print("buy 1 kg")

buy 1 kg


In [ ]:
a=10 #assign a value 10 to a variable a
b=20/2
a==b #compare the value of a with b 
tomatoprice=110
if tomatoprice==100:
    print("buy 1 kg")#indentation
else:
    print("buy 1/2 kg")
#string and no cant be compare    

In [ ]:
num=int(input("give any no of your choice"))
if num % 2 == 0:
    print("even")
else:
    print("odd")


In [ ]:
2+2 

In [ ]:
2-3.5

In [ ]:
5.5-4.5 

In [ ]:
1/1 #int divide by int give float

In [ ]:
1//1 #// is a symbol so that it gives answer in int

In [ ]:
5//2

In [ ]:
5/2

In [ ]:
print("print"*3)

In [ ]:
2**3 #**refer to power

In [ ]:
10!=20 #!= refer to not equal

In [ ]:
var1=100
if var1:
    print("1 - got a true expression value")  #it will not get on else statement bcz both are true so it will print on if
    print(var1)
else :
    print("1 - got a false exprssion value")
    print(var1)

In [ ]:
Meaning                Math Symbol       Python symbol
less than                  <                  <
greater than               >                  >
less than or equal         <                  <=
                           -
greater than or equal      >                  >=
                           -
equals                     =                   ==
not equals                                     !=

    

In [ ]:
name = input("enter your name=").upper()
if name=="RAZA":
    print("YOUR NAME IS:"+name)
else :
    print("no")
    

In [ ]:
temp=float(input("how much temprature? "))
if temp<25:
    print("wear pant.")
else :
    print("wear short")
print("get some exercise outside")    
            

In [ ]:
weight=float(input("how much your lugage weight? "))
if weight>50:
    print("there is a 25$ charge for your lugage its too heavy")
print ("thnx for your business")    
            

In [ ]:
x=float(input("enter your marks out of 100:"))
if x>=90:
    print("grade A*")
elif x>=80:
    print("grade A")
elif x>=70:
    print("grade B")
elif x>=60:
    print("grade C")
elif x>=50:
    print("grade D")
else :
    print("sorry you are fail")
   

In [ ]:
English=float(input("Enter your english marks:"))
urdu=float(input("Enter your urdu marks:"))
maths=float(input("Enter your maths marks:"))
programming=float(input("Enter your programming marks:"))
islamiat=float(input("Enter your islamiat marks:"))

total=English+urdu+maths+programming+islamiat

percentage=round(total/500*100,2)


grade="no grade issued"

if percentage>100:
    print("invalid input marks")
elif percentage>=90:
    grade= "A*"
elif percentage>=80:
    grade ="A"
elif percentage>=70:
    grade="B"
elif percentage>=60:
    grade="C"
elif percentage>=50:
    grade ="D"
else:
    print("you are fail")
    
print("your total marks are:",total,"\n","your total percentage",percentage,"\n",grade,sep="")

    





In [ ]:
Ijazat=input("\nAsk your mom.\nIs she allow you to go to stadium.[Y/N]").upper()
Ticket=input("do you have ticket for todays match?[Y/N]").upper()
Time=input("Are you free on Sunday?[Y/N]").upper()
if Ijazat=="Y" and Ticket=="Y" and Time=="Y":
    print("you are allow for the match")
else:
    print("sorry!!!")


In [ ]:
print("\t\t\t\t\t###CAST VOTE###")
age=int(input("whats your age:"))
RemainingAge=18-age

if age>=18:
    cnic =input("do you have your cnic card with you right now:[Y/N]").upper()
    voter_cast=input("is your name mention in voter casting list:[Y/N]").upper()
    if cnic=="Y" and voter_cast=="Y":
        print("Go!and cast your vote")
    else :
        print("sorry your vote cant be cast here")
else:
    print("\nyou are not officially able to cast vote")
    print("\nyou will be able to cast vote after"+" "+str(RemainingAge)+" "+"years")

In [ ]:
cycle=[]
cycle.append("1")
cycle.append("2")
cycle.append("3")
print(cycle)

In [ ]:
favorite_language=' python '
favorite_language.strip()

In [ ]:
mylist=["khi","lhr","isl","quetta","multan"]
#index=0,1,2,3,4,5,6,7,8,9,
#remove delete value vise
#del delete index vise

In [ ]:
print(mylist.index("lhr"))

In [ ]:
mylist.remove("khi")
print(mylist)

In [ ]:
name=" raza "
name.strip()

In [ ]:
TASK_LIST=["task1","task2","task3","task4","task5"]
DONE_LIST=[]

In [ ]:

user=input("Enter your taskNo")
if user in TASK_LIST:
    y=(TASK_LIST.index(user))
    user=TASK_LIST.pop(y)
    DONE_LIST.append(user)
    print(DONE_LIST)
    print(TASK_LIST)
else:
    print("this task is not in list")
    

In [ ]:
mylist=["khi","lhr","isl","quetta","multan"]


In [ ]:
#slicing
#[start:end]-1 from end 
#slicing always from left to right otherwise empty  bracket will be answer either in positive digit or negative one
mylist[3:5]

In [ ]:
list=[1, 2, 3, 4, 5, 6, 7, 8, 9]
slice1=list[2:5]
print(slice1)

In [ ]:
slice3=list[-5:-2]
print(slice3)

In [2]:
list=[9,8,7,6,5,4,3,2,1]
list.sort()
print(list)

[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [3]:
list=[1, 2, 3, 4, 5, 6, 7, 8, 9]
list.sort(reverse=True)
print(list)
#reverse in decending order
#reverse is bydefault false

[9, 8, 7, 6, 5, 4, 3, 2, 1]


In [4]:
mylist=["khi","lhr","isl","quetta","multan"]
mylist.sort(reverse=True)
print(mylist)
#sort fuction dont give us in return unlike popping
#dlice return you your list

['quetta', 'multan', 'lhr', 'khi', 'isl']


In [5]:
mylist=["khi","lhr","isl","quetta","multan"]
mylist.reverse()
print(mylist)

['multan', 'quetta', 'isl', 'lhr', 'khi']


In [ ]:
GUEST=["Ali","ahmed","farhan",]
print("Your are invited by me on dinner on wednesday",GUEST[0])
print("You are invited by me on dinner on wednesday",GUEST[1])
print("You are invited by me on dinner on wednesday",GUEST[2])


In [ ]:
GUEST.insert(0,"Younus")
GUEST.insert(2,"Raza")
GUEST.append("Amjad")
print("You are invited by me on dinner on wednesday",GUEST[0])
print("You are invited by me on dinner on wednesday",GUEST[1])
print("You are invited by me on dinner on wednesday",GUEST[2])
print("You are invited by me on dinner on wednesday",GUEST[3])

print("\t\t\t###I have a found a new big table### ")

print("You are invited by me on dinner on wednesday",GUEST[4])
print("You are invited by me on dinner on wednesday",GUEST[5])



In [ ]:
q=[1,4,4,4,2,3,4,5,6,7,8]

q.count(4)
q.count(8)

#no of same value in a list


In [ ]:
v=extend("raza")
print()


In [ ]:
a=[0,1,2,3,45,66,78,9]
sum(a)

In [ ]:
a[5]+a[6]

In [ ]:
q.extend("8888888")
print(q)

In [ ]:
for a in range(10):
    print(a, "PAKISTAN") 
    print("zindabad")

In [ ]:
for num in range(10,15):
    print(num,"raza")

In [ ]:
for num in range(1,10,2):    #steping(for function:shift+tab)
    print(num,"raza")

In [ ]:
list1=[11,22,"3",55,66,77,88,99,"raza",True,False]

In [ ]:
for num in list1:
    print(num,type(num))

In [ ]:
list=[11,22,33,44,55,66,77,88,99,]


In [ ]:
for num in list:
    if num%2!=1:
        print(num,"is even")
    else :
        print (str(num)+"is odd")

In [ ]:
oddList=[]
evenList=[]
messsage=""

list1=[1,2,3,4,5,6,7,8,9,10]

for num in list1:
    if num%2==0:
        evenList.append(num)
    else:
        oddList.append(num)
print("even")


In [ ]:
list1=[1,2,3,4,5,6,7,8,9,10]

In [ ]:
oddList=[]
evenList=[]
message=""

list1=[1,2,3,4,5,6,7,8,9,10]

for num in list1:
    if num%2!=0:
        oddList.append(num)
    else:
        evenList.append(num)
        
message+="These are odd numbers:"

for odd in oddList:
    message+=str(odd)+","
    
message+="and "

for even in evenList:
    message+=str(even)+","
    
message+="are even numbers"

print(message)

In [ ]:
even=[]
odd=[]

list1=[0,1,2,3,4,5,6,7,8,9]
for num in list1:
    if num%2==0:
        even.append(num)
    else :
        odd.append(num)
print("EVEN")
for ev in even:
    print(ev,end=",")#\n(by default) is replace by " " or ","
print("\nodd")   
for od in odd:
    print(od,end=",")

In [ ]:
friends=["ahmed","farhan","hammad","saleem","faheem","bilal"]
relative=["hamid","faizan","anas","hamza","samad","ahmed","farhan"]


#similar element home assignment 


       


In [ ]:
name=["hamid","faizan","anas","hamza","samad","ahmed","farhan"]
for names in name[2:]:
    print(names)

In [ ]:
name=["hamid","faizan","anas","hamza","samad","ahmed","farhan"]
for names in name[2:]:
    print(names.upper())

In [ ]:
print(r"c\doc\naveed")

In [ ]:
print('raza\'s book')

In [ ]:
friend_pizza=["pepparoni","double cheez"]
my_pizza=[]
for a in friend_pizza:
    my_pizza.append(a)


friend_pizza.append("tikka")
my_pizza.append("vegetable")

print("my favorite pizza are")
for c in my_pizza:
    print(c)
    
print("\nmy friends favorite pizza are")
for d in friend_pizza:
    print(d)
    

In [ ]:
current_user=["tariq","farhan","raza","ali","wasif","yousuf"]
new_user=["haseeb","husnain","hunain","hamza","ali","raza","imran","faizan"]


In [ ]:
for new_users in new_user:
    if new_users in current_user:
        print(new_users+" "+"already exist")
        print("enter new name\n ")
    else :
        print(new_users+" "+" is added to database\n")
        

In [ ]:
s="pakistan"   #slicing can also be perform on string just like list
               #can not perform rewrite or del on strings[2:3]
               #pythonstring.docs
               #pyhton-reference.readthedocs.io

In [ ]:
s="pakistan"
s.find("a")

In [ ]:
s.rfind("a")#last occuring 

In [ ]:
name="younus"
f_name="raza"
print("my friend name is {} and is father name is {}.".format(name,f_name))#formate

In [ ]:
name="younus"
f_name="raza"
print("my friend name is {0} and is father name is {0}. ".format(name,f_name))#formate

In [ ]:
name="younus"
f_name="raza"
print("my friend name is {1} and is father name is {1} .".format(name,f_name))#formate

In [ ]:
#new_method
print(f"my friend name is {name} and is father name is {f_name}.")

In [ ]:
num=45
name="asad"

print(f"my name is {name} and his age is {num}.")

In [ ]:
person="nasir"

In [ ]:
print("my name is {}".format(person))

In [ ]:
d={'a':123,'b':456,'c':789}

In [ ]:
print(f"my number is {d['a']}")

In [ ]:
mylist=[1,2,3]

In [ ]:
print(f"my number is {mylist[2]}")

In [ ]:
library=[('Author','Topic','Pages'),
        ('Nasir','DeepLearning',300),
        ('Ahmed','python',500),('Zia','kube',300)]

In [ ]:
library

In [ ]:
a=12,13,14,15 #packing of values

In [ ]:
a   #inform of tuple

In [ ]:
b,c=a  #unpack

In [ ]:
b,c,d,e=a

In [ ]:
b

In [ ]:
name="raza"
age="19"


In [ ]:
print("my name is {} and age is {}".format(name,age))

# TUPLE

In [ ]:
cities=("karachi","lahore","islmabad","quetta")

In [ ]:
print(cities)
print(type(cities))

In [ ]:
del cities

In [ ]:
print(cities)

In [ ]:
tup1=("phy","chem",1997,2000)
tup2=(1,2,3,4,5,6,7,8,9)
print("tup1[0]:",tup1[0:2])
print("tup2[1:5]:",tup2[1:5])


In [ ]:
tup1=(12,34.56)
tup2=("abc","xyz")

tup3=tup2+tup1
print(tup3)
print(type(tup3))

In [ ]:
tup=("physics","chemistry",1997,2000)
print(tup)
del tup
print("after deleting tup:")
print(tup)

In [ ]:
thistuple=("apple","banana","cherry")
thistuple[1]="blackcurrant"
print(thistuple)

In [ ]:
thistuple=("apple","banana","cherry")
for x in thistuple:
    print(x)

In [ ]:
thistuple=("apple","banana","cherry")
if "apple" in thistuple:
    print("yes,'apple in tuple'")

In [ ]:
thistuple=("blackberry","banana","cherry")
if "apple" in thistuple:
    print("yes,'apple in tuple'")
else:
    print("ERROR")

In [ ]:
thistuple=("blackberry","banana","cherry")
print(len(thistuple))


In [ ]:
tup3="a","b","c","d"
print(type(tup3))

# DICTIONARIES

In [ ]:
a=['key':'value']

In [ ]:
alien_0 = {'colour':'green','points':5}
print(alien_0['colour'])
print(alien_0['points'])


# DICT TYPE

In [ ]:
myDic={1:23,3:56,7:100}

In [ ]:
myDic1={1:"PK",2:"US"}

In [ ]:
myDic2={"name":"RAZA","f_name":"KHAN"}

In [ ]:
myDic3={"name":"Dhoraji","type":"ASSOCIATION","work":"ASSOCIATION"}

In [ ]:
myDic4={"type":"Dhoraji","type":"ASSOCIATION","work":"ASSOCIATION"}

In [ ]:
myDic4["type"]#overwrite value for type key

In [ ]:
myDic5={1:["PK","US","UNO"]} #LIST

In [ ]:
myDic6={1:("PK","US","UNO")} #TUPLE

In [ ]:
myDic6[1][2]

In [ ]:
myDic7={1:{11:111,22:222,33:333},2:{22:222,33:333,44:444}}

In [ ]:
myDic7[2][44]

In [ ]:
if 1 in{1:100,2:200}:
    print("hello")

# EXAMPLE

In [ ]:
alien_0 = {'colour':'green','points':5}
new_points=alien_0['points']
print("you just earned"+" "+str(new_points))

In [ ]:
alien_0={'colour':'green','points':5}
print(alien_0)
alien_0['x_position']=0
alien_0['y_position']=25
print(alien_0)

In [ ]:
foods={}
foods['Karachi']='favourite'
foods['sheep']='Boti Kabab'
foods['khawasa']='yummy'
foods['BBQ']='MALAI BOTI'
foods['shake']='choclate'
foods['ice creame']=" 12"

print(foods)

In [ ]:

foods['ice Cream']={"a":["apple","orange","mango"],"b":["11","22","33"],"c":["biryani","cheery","kabab"]}

In [ ]:
print(foods['ice Cream']["c"][2])

In [ ]:
players={'Watson':'Australian International Cricketer'}
print("SHANE ROBERT WATSON is a "+players['Watson'].upper()+'.')

In [ ]:
psl = {"Karachi":"Kings" , "Multan":"sultan" , "zalmi" : "won"}
print("Karachi is a : " + str(psl["Karachi"]))

if psl["zalmi"]=="loser":
    x_increment = 1
    
elif psl["zalmi"]=="won":
    x_increment = 2
    
psl["zalmi"]=psl["zalmi"] + str(x_increment)
print("PSL 4 zalmi : " + str(psl["zalmi"]))

In [ ]:
alien_0 = {'colour':"green",'colour1':"blue",'points':50}

if alien_0['points']==0:
    x_increment =-1
    
elif alien_0['points']==25:
    x_increment = 2
else :
    print("high score")
    
    

print("YOUR POINTS ARE" + str(alien_0)
    

# 15 APRIL DICTIONARY


In [ ]:
dict1={"a":11,"b":20,"c":30}
for key1,value1 in dict1.items():
    print(key1,value1)

In [ ]:
for key1 in dict1.keys():
    print(key1)

In [ ]:
for key1 in dict1.values():
    print(key1)

In [ ]:
favorite_language={"raza":"python","anas":"java","waseem":"c++","faheem":"ruby"}
print("Raza favorite language is "+favorite_language["raza"]+" .")
print("Anas favorite language is "+favorite_language["anas"]+" .")


In [ ]:
Information={"First_name":"Younus","Last_name":"Raza","Age":19,"City":"Karchi"}

print("FIRST NAME:"+Information["First_name"]+"\n"+"LAST NAME:"+Information["Last_name"]+"\n"+"Age:"+str(Information["Age"])+"\n"+":"+Information["City"])

In [14]:
Information={"First_name":"Younus","Last_name":"Raza","Age":19,"City":"Karchi"}


In [20]:
print("my favourite language is {}".format(Information["First_name"]))
print("my favourite language is {}".format(Information["Last_name"]))
print("my favourite language is {}".format(Information["Age"]))
print("my favourite language is {}".format(Information["City"]))

my favourite language is Younus
my favourite language is Raza
my favourite language is 19
my favourite language is Karchi


# LOOPING THROUGH DICT

In [27]:
names={"shahzad":"ahsan","sara ali":"khan","yaqoob":"farhan","younus":"raza"}
for first_name,last_name in names.items():
    print("my first Name is "+first_name.title()+" and my last name is "+last_name+".")

my first Name is Shahzad and my last name is ahsan.
my first Name is Sara Ali and my last name is khan.
my first Name is Yaqoob and my last name is farhan.
my first Name is Younus and my last name is raza.


# LOOPING THROUGH ALL THE KEYS IN A DICT


In [30]:
words={"mobile":"apple" , "batsman":"AB" ,"bike":"heavy" ,"car":"audi"}

for word in words.values():
    print("Dict:"+word)

Dict:apple
Dict:AB
Dict:heavy
Dict:audi


In [32]:
user_0={"teacher":"Sir Nasir","Teacher_assistant":"shahxad","student":"ali"}

In [38]:
for key,value in user_0.items():
    print("\nkey:"+key)
    print("Vlue:"+value)


key:teacher
Vlue:Sir Nasir

key:Teacher_assistant
Vlue:shahxad

key:student
Vlue:ali


In [6]:
alien1 ={"name":"alien","colour":"green","height":"5.7","weight":"67"}

In [16]:
if "last_name" not in  alien1.keys():
    print("please write your last name...")

NameError: name 'alien1' is not defined

In [17]:
name1={'sheryar':'zafar','younus':'raza','zaidi':'farhan','owais':'rafiq','muhammad':'zafar'}

In [18]:
for new_names in sorted(name1.keys()):
    print(new_names.upper()+',have a good day')
print(name1)    

MUHAMMAD,have a good day
OWAIS,have a good day
SHERYAR,have a good day
YOUNUS,have a good day
ZAIDI,have a good day
{'sheryar': 'zafar', 'younus': 'raza', 'zaidi': 'farhan', 'owais': 'rafiq', 'muhammad': 'zafar'}


In [37]:
raza=[1111,2,3,34,45,56,67]
q=sorted(raza,reverse=True)   #in sort function we dont get anything in result
                 #in sorted function we dont get anything in result

In [25]:
print(q)

[1111, 67, 56, 45, 34, 3, 2]


In [34]:
# For list 
seqList = [1, 2, 4, 3, 5] 
print(reversed(seqList))

# A LIST OF DICT
'

In [77]:
alien_0={'colour':'green','points':5}
alien_1={'colour':'yellow','points':10}
alien_2={'colour':'blue','points':15}

aliens=[alien_0,alien_1,alien_2]
for alien in aliens:
    for key,value in alien.items():
        print(key,value)    #nested loop


colour green
points 5
colour yellow
points 10
colour blue
points 15


In [10]:
numbers=[1,2,3,4,5,6,7,8,9,10]
for table in [2]:
    for num in numbers:
        print(f"{table} * {num}={table*num}")  #nested loop #tables

2 * 1=2
2 * 2=4
2 * 3=6
2 * 4=8
2 * 5=10
2 * 6=12
2 * 7=14
2 * 8=16
2 * 9=18
2 * 10=20


# DICTIONARY IN DICTIONARY

In [16]:
users={'sheikh':{'first':'shahxzad','last':'ahsan','location':'bahadurabad',},'sir':{'first':'nasir','last':'husain','location':'gulshan',}}
for username ,user_info in users.items():
    print("\nUsername: "+username)
    full_name=user_info['first'] + " "+user_info['last']
    location=user_info['location']
    print("\tFull_name: "+full_name.title())
    print("\tlocation: "+location.title())


Username: sheikh
	Full_name: Shahxzad Ahsan
	location: Bahadurabad

Username: sir
	Full_name: Nasir Husain
	location: Gulshan


# WHILE LOOP

In [2]:
a=10
while a>0:
    print(a,"Hello")
    a -=1


10 Hello
9 Hello
8 Hello
7 Hello
6 Hello
5 Hello
4 Hello
3 Hello
2 Hello
1 Hello


In [7]:
a=10
while a>=0:
    print(a,"Hello")
    a -=1

10 Hello
9 Hello
8 Hello
7 Hello
6 Hello
5 Hello
4 Hello
3 Hello
2 Hello
1 Hello
0 Hello


In [8]:
for a in range(0,10):
    print(a,"HELLO")

0 HELLO
1 HELLO
2 HELLO
3 HELLO
4 HELLO
5 HELLO
6 HELLO
7 HELLO
8 HELLO
9 HELLO


In [1]:
a=2
while a<=10:
    print(a)
    a+=2

2
4
6
8
10


In [9]:
a=int(input())
while a<10:
    if a%2==0:
        print(a+2)
        a+=2
    else:
        print(a+2)
        a+=2

2
4
6
8
10


In [ ]:
num=int(input("enter number: "))
while num==9:
    print("nine is entered")
    

In [ ]:
condition=True
while condition:
    num=input("enter number: ")
    if num=='q':
        print("TERMINATED")
        condition=False
    else :
        print("THe square of number is",int(num)**2)

enter number: 23
THe square of number is 529
enter number: 36
THe square of number is 1296
enter number: 32
THe square of number is 1024
enter number: 35
THe square of number is 1225
enter number: 25
THe square of number is 625


In [ ]:
while True:
    num=int(input("GIVE YOUR FIRST NUMBER: "))
    num1=int(input("GIVE YOUR SECOND NUMBER: "+"\n"))
    num2=input("PRESS 1 FOR ADDITION"+"\n"+"PRESS 2 FOR SUBTRATION"+"\n"+"PRESS 3 FOR MULITIPLICATION"+"\n"+"PRESS 4 FOR DIVISION")
    if num2=="1":
        ADD=num+num1
        print
    elif num2=="2":
        SUBTRACT=num-num1
        print(SUBTRACT)
    elif num2=="3":
        MULTIPLY=num*num1
        print(MULTIPLY)
    else :
        DIVIDE=num/num1
        print(DIVIDE)
    
    #if and elif shpuld be in the same body 

GIVE YOUR FIRST NUMBER: 12
GIVE YOUR SECOND NUMBER: 
12
PRESS 1 FOR ADDITION
PRESS 2 FOR SUBTRATION
PRESS 3 FOR MULITIPLICATION
PRESS 4 FOR DIVISION1


In [14]:
print("GIVE YOUR PIZZA ORDER")
topping=[]
while True:
    a=input("What flavour you want..... ")
    if a=='quit':
        break
    else:
        print("You order flavour:"+a )
        break
while True:
    
    b=input("what size you want: ")
    if b=="quit":
        break
    else:
        print("your selected size is:"+b )
        break
while True:
    c=input("select topping :")
    if c=="quit":
        break
    else:
        topping.append(c)
for z in topping:
    print(z)
    
        

#print("\nyou order pizza is of flavour :"+a)
#print("you order pizza is of size:"+b)
#print ("you order pizza is of topping :"+c)


    



GIVE YOUR PIZZA ORDER
What flavour you want..... chicken
You order flavour:chicken
what size you want: large
your selected size is:large
select topping :1
select topping :
select topping :21
select topping :quit
1

21


In [1]:
4%2


0

In [2]:
string="younus"
string[2:5]

'unu'

In [4]:
string="younus"
string[5:2]

''

In [5]:
string="younus"
string[-1:-4]

''

In [6]:
string="younus"
string[-4:-1]


'unu'

In [7]:
string="younus"
string[::2]

'yuu'

In [8]:
string="younus"
string[::-1]

'sunuoy'

# TEST CODE

In [19]:
for i in range(10):
    if i==5:
        break
    else:
        print(i)
else:
    print("here")

0
1
2
3
4


In [20]:
for i in range(10):
    if i==15:
        break
    else:
        print(i)
else:
    print("here")

0
1
2
3
4
5
6
7
8
9
here


In [28]:
x=(i for i in range (3) )
for i in x:
    print(i)

0
1
2


In [3]:
string="my name is x"
for i in string.split():#here in this() we have to pass any variable from where we have to split
    print(i,end=",")

my,name,is,x,

In [8]:
string="my name is x"
for i in string.split():
    print(i,end=",")

my,name,is,x,

In [11]:
a=[0,1,2,3]
i=-2
for i not in a:
    print(i)
    i+=1

SyntaxError: invalid syntax (<ipython-input-11-01a53513db72>, line 3)

In [22]:
l=["good","oh!","ecellent!","#450"]
[n for n in l if n.isalpha() or n.isdigit()]

['good']

In [27]:
s1=[6,7]
s2=[11,15]
s3=list()
i=0
j=0
for i in s1:
    for  j in s2:
        s3.append((i,j))
        i+=1 #IMP POINTS
        j+=1 #IMP POINTS
print(s3)        

[(6, 11), (7, 15), (7, 11), (8, 15)]


In [34]:
a={}   #here we make a dictionary
a[2]=1
a[1]=[2,3,4]
print(a)
print(a[1])
print(a[1][1])

{2: 1, 1: [2, 3, 4]}
[2, 3, 4]
3


In [35]:
a=[1,12,3,4,5]
a.clear()
print(a)

[]


In [36]:
#in pop function we have to pass argument in dict but not in list

In [38]:
a=[1,2,3,4,5,6,7,1,2,23,4,5,56]
c=set(a)#shortest way to remove duplicate
print(c)

{1, 2, 3, 4, 5, 6, 7, 23, 56}


In [6]:
string="younus,raza,fasih"
raza,age,name=string.split(",")

In [7]:
print(raza)
print(age)
print(name)

younus
raza
fasih


In [9]:
liss=["younus","raza"]
(",".join (liss))

'younus,raza'

# FUNCTION

In [10]:
def function1():
    print("HEllo FUnction")

In [11]:
function1()

HEllo FUnction


In [27]:
def odd_even(n):
    if n%2==0:
        print("even")
    else:
        print("odd")

In [28]:
num=int(input("ENTER A NUMBER:"))
odd_even(num)

ENTER A NUMBER:2
even


In [29]:
num=int(input("ENTER A NUMBER:"))
odd_even(num)

ENTER A NUMBER:45
odd


In [10]:
def name(myname):
    print("hello",myname,"!")
    print(myname)

In [11]:
name("younus")

hello younus !
younus


In [12]:
def sum1(a,b,c):
    return a*b-c

d=sum1(4,5,2)
print(d)

18


In [13]:
sum1(5,10,15) #POSITIONAL ARGUENT

35

In [14]:
def addition(a,b):
    c=a+b
    return(c)
    
d=addition(5,5) 
print(d+2)

12


In [15]:
def result(name,m1,m2,m3):
    print("\t\t\t*****RESULT*****")
    print("\nSTUDENT NAME IS:"+name)
    total_marks=int(m1)+int(m2)+int(m3)
    
    print("TOTAL MARKS ARE:"+str(total_marks))
    if total_marks>=240:
        return("A+ grade")
    elif total_marks<240:
        return('A grade')
    else:
        return('fail')
        
        
   
    
    
    

In [16]:
name=input("enter your name:")
m1=input("marks in english subject:")
m2=input("marks in physics subject:")
m3=input("marks in maths subject:")


result(name,m1,m2,m3)

enter your name:
marks in english subject:
marks in physics subject:
marks in maths subject:
			*****RESULT*****

STUDENT NAME IS:


ValueError: invalid literal for int() with base 10: ''

In [20]:
def couples(hname,wname):
    print(f"The name of the husband is :{hname} and the name of the wife is: {wname} .")

In [21]:
couples("ahmed","wania")

The name of the husband is :ahmed and the name of the wife is: wania .


In [22]:
couples(wname="fatima",hname="ahmed")  #KEYTWORD ARGUMNET

The name of the husband is :ahmed and the name of the wife is: fatima .


In [23]:
def my_info(name,age):
    print(f"my name is {name}.")
    print(f"I am {age} years old.")

In [24]:
my_info("raza",19)

my name is raza.
I am 19 years old.


In [3]:
def cal():
    print("\t\t\t\tCALCULATOR")
    print("PRESS A TO ADD")
    print("PRESS B TO SUBTRACT")
    print("PRESS C TO MULTIPLY")
    print("PRESS D TO DIVIDE")
    print("PRESS QUIT TO EXIT \n")
    while True:
        a=int(input("enter a number:"))
        b=int(input("enter a number:"))
        opera=input("what function you want to perform: ")
        if opera=="A":
            c=a+b
            print(c)
        elif opera=="B":
            c=a-b
            print(c)
        elif opera=="C":
            c=a*b
            print(c)
        elif opera=="D":
            c=a/b
            print(c)
        elif opera=="QUIT":
            break
        else:
            print("invalid operator")

In [4]:
cal()

				CALCULATOR
PRESS A TO ADD
PRESS B TO SUBTRACT
PRESS C TO MULTIPLY
PRESS D TO DIVIDE
PRESS QUIT TO EXIT 

enter a number:5
enter a number:5
what function you want to perform: QUIT


# LIST IN A FUNCTION 

In [14]:
def my_list(a):
    for list_1 in a:
        print("hello",list_1)

In [27]:
def cal(a,b,c):
    if c=="+":
        return(a+b)
    elif c=="-":
        return(a-b)
    elif c=="*":
        return(a*b)
    elif c=="/":
        return(a/b)
    else:
        print("INVALID OPERATION ")

In [4]:
def family(s_name,f_name):  ##keyword argument
    print(f"father name is {f_name}")
    print(f"son name is {s_name}")

In [5]:
family(f_name="yousuf",s_name="younus")

father name is yousuf
son name is younus


In [6]:
def friend(a):
    for b in a:
        print(b)

In [7]:
c=["raza","younus","ahsan","fahad","saleem"]

friend(c)

raza
younus
ahsan
fahad
saleem


In [22]:
def my_full_name(f_name,l_name,m_name=" "):
    if m_name:
        print(f"MY FULL NAME IS {f_name.upper()} {l_name.upper()} {m_name.upper()}")
    else:
        print(f"MY FULL NAME IS {f_name} {l_name} {m_name}")
        

In [23]:
 my_full_name("muhammad","younus","raza")

MY FULL NAME IS MUHAMMAD YOUNUS RAZA


In [24]:
my_full_name("muhammad","younus")

MY FULL NAME IS MUHAMMAD YOUNUS  


In [30]:
def tax(shopping,tax=5):
    if shopping>=5000:
        tax=10
        print(f"TAX {tax}% WILL BE APPLIED ON YOUR SHOPPING")
    else:
        print(f"TAX {tax}% WILL BE APPLIED ON YOUR SHOPPING")

In [31]:
tax(5000)

TAX 10% WILL BE APPLIED ON YOUR SHOPPING


In [32]:
tax(4999)

TAX 5% WILL BE APPLIED ON YOUR SHOPPING


In [52]:
def number(*n):
    total=0
    for a in n:
        total+=a
    return total    

In [53]:
number(1,2,3,4,5)

15

In [3]:
def mycar(name,company='HONDA',MODEL=2012):  #DEFAULT PARAMETER
    print("I have a",name,".")
    print("Its company is ",company)
    
mycar("city")    
    

I have a city .
Its company is  HONDA


In [5]:
def shirt(size,text="APNA TIME AYGA!"):
    print("THE SIZE OF MY SHORT IS :",size)
    print("the text i want to write on it is:",text)
shirt(33)

THE SIZE OF MY SHORT IS : 33
the text i want to write on it is: APNA TIME AYGA!


In [58]:
def info(f_name,l_name,m_name=""):
    if m_name:
        full_name=f_name+" "+m_name+" "+l_name
    else:
        full_name=f_name+" "+l_name
    return full_name    
  

In [59]:
a=info("younus","raza")
print(a)

younus  raza


In [60]:
b=info("muhammad","younus",'raza')
print(b)

muhammad younus


In [71]:
def info_form(f_name,l_name,m_name="",age=0,location=""):
    if m_name or age or location:
        print("FIRST_NAME:",f_name,"\nMIDDLE_NAME:",m_name,"\nLAST_NAME:",l_name,"\nAGE:",str(age),"\nLOCATION:",location)
    else:
         print("FIRST_NAME:",f_name,"\nLAST_NAME:",l_name)
        

In [72]:
info_form("muhammad","younus","raza",19,"dhoraji")

FIRST_NAME: muhammad 
MIDDLE_NAME: raza 
LAST_NAME: younus 
AGE: 19 
LOCATION: dhoraji


In [79]:
def pizza(topping):
    print("***HERE IS YOUR PIZZA***")
    for toppings in topping:
        print(toppings)
pizza("cheese")        

***HERE IS YOUR PIZZA***
c
h
e
e
s
e


# * and ** function

In [88]:
def pizza(*topping):
    print(topping) #tupple
    print("***HERE IS YOUR PIZZA***")
    for toppings in topping:
        print(toppings)
pizza("cheese","olive",'mashroom')

('cheese', 'olive', 'mashroom')
***HERE IS YOUR PIZZA***
cheese
olive
mashroom


In [89]:
##*will give in tuple form
##**will give in list or dict form

In [90]:
def pizza(a,*topping):
    print("***HERE IS YOUR PIZZA***")
    print(a)
    for toppings in topping:
        print(toppings)
pizza("cheese","olive",'mashroom')

***HERE IS YOUR PIZZA***
cheese
olive
mashroom


In [93]:
def kababjees(food,*drink,**sweet_dish):
    print(food,drink[0],sweet_dish)
   
kababjees("Malai botti","Pepsi",end=["ice cream","chocloate"])

Malai botti Pepsi {'end': ['ice cream', 'chocloate']}


# LIST COMPREHENSION

In [3]:
elist=[]
for a in range (0,30):
    if a%2==0:
        elist.append(a)
print(elist)        

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28]


In [4]:
#WE CAN WRITE WHOLE IN SHORT FORM TO AVOID LINE WAISTING

In [8]:
elist=[a for a in range(0,30) if a%2==0]

elist

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28]

In [10]:
[ x**2 for x in range(1,10)]

[1, 4, 9, 16, 25, 36, 49, 64, 81]

In [11]:
[a for a in range(1,30) if a%2!=0]

[1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29]

In [30]:
[(x,y) for x in [1,2,3] for y in [3,1,4] if x!=y]

[(1, 3), (1, 4), (2, 3), (2, 1), (2, 4), (3, 1), (3, 4)]

# EXAMPLE

In [35]:
vec=[-4,-2,0,2,4]

In [37]:
[x*2 for x in vec]

[-8, -4, 0, 4, 8]

In [38]:
[x for x in vec if x>=0]

[0, 2, 4]

## absolute function 

In [39]:
[abs(a) for a in vec]

[4, 2, 0, 2, 4]

In [41]:
freshfruit=[' banana ',' apple ',' pineapple ']
[weapon.strip() for weapon in freshfruit ]

['banana', 'apple', 'pineapple']

In [42]:
#create a 2-tuple of number and square

In [52]:
[(x,x**2) for x in range(0,11) ]

[(0, 0),
 (1, 1),
 (2, 4),
 (3, 9),
 (4, 16),
 (5, 25),
 (6, 36),
 (7, 49),
 (8, 64),
 (9, 81),
 (10, 100)]

In [53]:
#flatten a list using a listcomp with two "for"

In [54]:
vec = [[1,2,3], [4,5,6], [7,8,9]]
[num for elem in vec for num in elem]

[1, 2, 3, 4, 5, 6, 7, 8, 9]

# EXTRA FUNCTION

In [58]:
name.center(30)   #30 is the total no of gaps

'           shahzad            '

In [59]:
name.ljust(25,'-')

'shahzad------------------'

In [60]:
name.rjust(25,'-')

'------------------shahzad'

In [68]:
vec = [[1,2,3], [4,5,6], [7,8,9]]

In [71]:
a=[]
for elem in vec:
    for num in elem:
        a.append(num)
        

In [111]:
print(a)

[1, 2, 3, 4, 5, 6, 7, 8, 9]


# OBJECT

## CLASSES

In [ ]:
human
animal
tree
vehicle
building
machine
food
clothes
matter

In [6]:
class dog():   #behaviour as function and variable as property
    def bark(): #pass is use to set an empty class and function
        pass
    def run():
        pass


# MAKING A CLASS

In [34]:
class dog():
    def __init__(self,name,age):
        self.name=name
        self.age=age
    def sit(self):
        print(self.name.title()+" "+" is now sitting")
    def rol_over(self):
        print(self.name.title+"rolled over!")

## CREATING A CLASS

In [36]:
a=dog("tommy",5)

In [37]:
b=dog("Helli",4)

In [38]:
c=dog("abcd",3)

In [39]:
a.name

'tommy'

In [40]:
c.name

'abcd'

In [41]:
c.sit()

Abcd  is now sitting


In [67]:
class car():
    def __init__(self,model_name,colour,seating_capacity):
        self.model_name=model_name
        self.colour=colour
        self.seating_capacity=seating_capacity
    def run(self):
        print(self.model_name +" "+"can run at high speed")
    

In [68]:
mehran=car("mehran_2006","red","4")

In [69]:
mehran.model_name

'mehran_2006'

In [70]:
mehran.run()

mehran_2006 can run at high speed


In [18]:
class resturant():
    def __init__(self,name,cuisine_type,open_close):
        self.name=name
        self.cuisine_type=cuisine_type
        self.open_close=open_close
        self.number_served=10
    def describe_resturant(self):
        print(f"returant name is {self.name} and cuisine type is {self.cuisine_type}")
        
    def open_returant(self):
        print(f"resturant is {self.open_close}")
        
    def set_number_served(self,coustomer_served):
        self.number_served=coustomer_served
        return(f"YOUR RESTURANT HAS SERVED {self.number_served} COUSTOMER TODAY.")
    
    def increament_number(self,number_serve):
        self.number_served+=number_serve
        return(f"YOUR RESTURANT HAS SERVED {self.number_served} COUSTOMER TODAY.")
        

In [12]:
a=resturant("HotNroll","fast_food","open")

In [13]:
a.name

'HotNroll'

In [14]:
a.describe_resturant()

returant name is HotNroll and cuisine type is fast_food


In [15]:
a.number_served

10

In [16]:
a.set_number_served(22)

'YOUR RESTURANT HAS SERVED 22 COUSTOMER TODAY.'

In [17]:
a.increament_number(23)

'YOUR RESTURANT HAS SERVED 45 COUSTOMER TODAY.'

In [79]:
class mobile():
    def __init__(self,model,RAM,ROM,colour,front_camera,back_camera):
        self.model=model
        self.RAM=RAM
        self.ROM=ROM
        self.colour=colour
        self.front_camera=front_camera
        self.back_camera=back_camera
        self.gurantee_remaining=2 
    def water_proof(self):
        print(f"samsung {self.model}, in {self.colour} is waterproof")
    def unbreakable_glass(self):
        print(f"samsung{self.model},in {self.colour} has an unbreakable glass.")
    def update_life_use(self,used_life):
        self.gurantee_remaining=2-used_life
    def read_gurantee_remainig(self):
        print("this mobile has"+" "+str(self.gurantee_remaining)+" "+" "+"year"+" "+"remaining")
    

In [80]:
samsung=mobile("J7","64","32","BLACK","16MP","22MP")

In [81]:
samsung.model

'J7'

In [82]:
samsung.colour

'BLACK'

In [83]:
samsung.water_proof()

samsung J7, in BLACK is waterproof


In [84]:
samsung.unbreakable_glass()

samsungJ7,in BLACK has an unbreakable glass.


In [85]:
samsung.update_life_use(1)

In [86]:
samsung.read_gurantee_remainig()

this mobile has 1  year remaining


In [1]:
class Patient():
    pass

In [5]:
class Patient():
    def __init__(self,last_name):
        self.last_name=last_name
        pass

In [6]:
pid4343=Patient("Taleb")

In [4]:
pid4344=Patient("ahsan")
pid4355=Patient("siraj")
pid4444=Patient("faraz")

In [11]:
class patient():
    def __init__(self,last_name,first_name,age):
        self.last_name=last_name
        self.first_name=first_name
        self.age=age
        

In [14]:
pid2222=patient("shahid","anas",34)
pid4355=patient("siraj","faisal",45)
pid4444=patient("faraz","amajad",34)

In [15]:
pid4444.last_name

'faraz'

In [1]:
class car():
    def __init__(self,make,model,year):
        self.make=make
        self.model=model
        self.year=year
        self.odometer_reading=0
        
    def get_descriptive_name(self):
        long_name=str(self.year)+" "+self.make+" "+self.model
        return long_name.title()
    
    def read_odometer(self):
        print("This car has "+str(self.odometer_reading)+" "+"miles on it.")
        
    def update_odometer(self,mileage):
        self.odometer_reading=mileage

In [4]:
my_new_car=car("audi","a4",2016)
my_new_car.update_odometer(60)
my_new_car.read_odometer()

This car has 60 miles on it.


In [3]:
my_new_car.get_descriptive_name()

'2016 Audi A4'

In [40]:
class Dog():
    def __init__(self,name,age):
        self.name=name
        self.age=age
    @property    
    def sit(self):
        print(self.name.title()+" "+"is now sitting .")
    def roll_over(self):
        print(self.name.title() +" "+ "rolled over!")

In [41]:
my_dog=Dog('willie', 6)
your_dog=Dog("lucy",3)

In [42]:
my_dog.name

'willie'

In [43]:
my_dog.sit

Willie is now sitting .


In [44]:
my_dog.roll_over()

Willie rolled over!


In [45]:
your_dog.name

'lucy'

In [46]:
your_dog.roll_over()

Lucy rolled over!


In [2]:
class resturant():
    def __init__(self,name,cuisine_type,open_close):
        self.name=name
        self.cuisine_type=cuisine_type
        self.open_close=open_close
    def describe_resturant(self):
        print(f"returant name is {self.name} and cuisine type is {self.cuisine_type}")
    def open_returant(self):
        print(f"resturant is {self.open_close}")

In [1]:
class car():
    def __init__(self,make,model,year):
        self.make=make
        self.model=model
        self.year=year
        self.odometer_reading=0
    def get_descriptive_name(self):
        long_name=str(self.year)+" "+self.make+" "+self.model
        return long_name.title()
    def read_odometer(self):
        print("This car has "+str(self.odometer_reading)+" miles on it.")
    def increment_odometer(self,mile):
        self.odometer_reading+=mile
    def update_odometer(self,mileage):
        if mileage>=self.odometer_reading:
            self.odometer_reading=mileage
        else:
            print("You cant roll back on odometer")
        return (f'Now car is showing {self.odometer_reading} mileage on it')

In [18]:
my_new_car=car('audi',"a4",2016)
print(my_new_car.get_descriptive_name())

2016 Audi A4


In [19]:
my_new_car. update_odometer(60)

'Now car is showing 60 mileage on it'

In [20]:
my_new_car.update_odometer(40)

You cant roll back on odometer


'Now car is showing 60 mileage on it'

In [21]:
my_new_car.increment_odometer(20)

# INHERITENCE

In [6]:
class car():
    def __init__(self,make,model,year):
        self.make=make
        self.model=model
        self.year=year
        self.odometer_reading=0
    def get_descriptive_name(self):
        long_name=str(self.year)+" "+self.make+" "+self.model
        return long_name.title()
    def fill_gas(self):
        print("the gas tank is fill")
    def read_odometer(self):
        print("This car has "+str(self.odometer_reading)+" miles on it.")
    def increment_odometer(self,mile):
        self.odometer_reading+=mile
    def update_odometer(self,mileage):
        if mileage>=self.odometer_reading:
            self.odometer_reading=mileage
        else:
            print("You cant roll back on odometer")
        return (f'Now car is showing {self.odometer_reading} mileage on it')
    

In [14]:
class electric_car(car):
    def __init__(self,make,model,year):
        super().__init__(make,model,year)  #HERE BATTERY IS GOING VERY LONG SO WE ARE MA
        self.battery_size=70
        self.manufacturer=" "
        self.cycles=" "
        self.no_of_pallets=" "
        self.amperes=" "
        
        
    def describe_battery(self):
        print(f"THIS CAR HAS A { self.battery_size}  -KWH BATTERY ")
        
    def fill_gas(self):
        print("ELECTRIC CAR DOESNT NEED GAS")    
        
        
        
my_tesla=electric_car("tesla",",Model s",2016)
print(my_tesla.get_descriptive_name())

my_tesla.describe_battery()
my_tesla.fill_gas()


2016 Tesla ,Model S
THIS CAR HAS A 70  -KWH BATTERY 
ELECTRIC CAR DOESNT NEED GAS


In [7]:
class Battery():
    def __init__(self,amperes,no_of_pallets,cycles,manufacturer,battery_size=70):
        self.battery_size=battery_size
        self.manufacturer=manufacturer
        self.cycles=cycles
        self.no_of_pallets=no_of_pallets
        self.amperes=amperes
        
    def describe_battery(self):
        print(f"THIS CAR HAS A { self.battery_size}  -KWH BATTERY ")    
        
        

In [18]:
class electric_car(car):
    def __init__(self,make,model,year):
        super().__init__(make,model,year)  #HERE BATTERY IS GOING VERY LONG SO WE ARE HAVE MADE A NEW CLASS AND THAN LINK IT WITH IT
        self.battery=Battery(100,5,6,"osaka")
        
    
        
    def fill_gas(self):
        print("ELECTRIC CAR DOESNT NEED GAS")    
        
        


In [20]:
my_tesla=electric_car("tesla","model s",2016)
my_tesla.battery.describe_battery()

THIS CAR HAS A 70  -KWH BATTERY 


In [4]:
blocks=int(input("Enter No Of Blocks"))
chk=1
adder=2
height=0
while chk<=blocks:
    chk+=adder
    adder+=1
    height+=1
print("Height",height)    

Enter No Of Blocks6
Height 3


# MODULES

In [11]:
import math2

In [13]:
math2.add_list([2,3,4])

9

In [25]:
from car import Car,electric_car

In [26]:
toyota=Car("Toyota","FX",2002)
my_tesla=electric_car("tesla","model s",2016)

In [27]:
my_tesla.describe_battery()

THIS CAR HAS A 70  -KWH BATTERY 


# File and Excemption

In [56]:
with open("abcd.txt") as file_object:
    contents = file_object.read()
    print(contents)

hello my name is pakistan


In [57]:
with open ("abcd1.txt","w") as f:
    f.write("HELLO PYTHON")   #by help of w  if file does not exist it will make it
                             #it will overwrite the previous data if we write on existing data

In [58]:
with open("abcd1.txt") as file_object:
    contents = file_object.read()
    print(contents)

HELLO PYTHON


In [59]:
with open("abcd.txt","r") as file_object:
    contents = file_object.read()
    print(contents)

hello my name is pakistan


In [63]:
with open ("abcd.txt","a") as file:
    c=file.write("hehhe")
    

In [64]:
with open("abcd.txt") as file_object:
    contents = file_object.read()
    print(contents)

hello my name is pakistanhehhehehhe


In [69]:
#if we use r+ it will go for read write mode both it will not create self file

In [2]:
with open("abcd.txt","r+") as g:
    g.write("123")
    g.seek(0)
    t=g.read()
    print(t)
#to strt cursor with start seek is use
#bcz cursor will strt next function at same time 

123loo my name is pakistan


In [7]:
with open("abcd.txt","r") as file_object:
    contents = file_object.read()
    print(contents)

123lo my name is pakistan


In [3]:
myfile=open("hello.txt","r")  #here first line is not writing

In [20]:
for line in myfile:
    cont=myfile.readlines()
    print(cont)

['raza\n', 'younus\n', '++++']


In [21]:
cont

['raza\n', 'younus\n', '++++']

In [6]:
m=open("greeting.txt","r")

In [7]:
for line in m:
    cont=m.readlines()
    print(cont)

['raza\n', '123\n', '123456789\n']


In [8]:
cont

['raza\n', '123\n', '123456789\n']

In [10]:
with open("math.txt") as file_object:
    contents=file_object.read()
print(contents)    

3.1415926535
8979323846
2643383279


In [11]:
print(contents.rstrip())

3.1415926535
8979323846
2643383279


In [13]:
pi="math.txt"
with open (pi) as file_object:
    for line in file_object:
        print(line)
    

3.1415926535

8979323846

2643383279


In [16]:
file="math.txt"
with open(file) as a:
    lines=a.readlines()
for line in lines:
    print(line.rstrip())

3.1415926535
8979323846
2643383279


In [18]:
file="math.txt"
with open (file) as file_object:
    lines=file_object.readlines()
pi=''
for line in lines:
    pi+=line.strip()
print(pi)
print(len(pi))

3.141592653589793238462643383279
32


# EXCEPTION

In [19]:
#they are logical error

In [21]:
5/0 #cant be divide be zero 
#program will be crashed due to exception
print("hell")

ZeroDivisionError: division by zero

In [2]:

#EXCEPTION HANDLING

a=int(input("ENTER A NUMBER:"))
b=int(input("ENTER A NUMBER:"))
try:
    c=a/b #where exception can be raised is written in try block
    print(c)
except ZeroDivisionError: #if exception is raised is written in except block
    print("Exception is caught   ZeroDivisionError ")
    

ENTER A NUMBER:1
ENTER A NUMBER:0
Exception is caught   ZeroDivisionError 


In [1]:
a=int(input("ENTER A NUMBER:"))
b=int(input("ENTER A NUMBER:"))
try:
    c=a/b #where exception can be raised is written in try block  
except ZeroDivisionError: #if exception is raised is written in except block
    print("Exception is caught   ZeroDivisionError ")
else:
    print(c)
    
            

ENTER A NUMBER:3
ENTER A NUMBER:4
0.75


In [3]:
a=int(input("ENTER A NUMBER:"))
b=int(input("ENTER A NUMBER:"))
try:
    c=a/b 
    print(c)
except ZeroDivisionError:
    print("Exception is caught   ZeroDivisionError ")

print("last")    
            

ENTER A NUMBER:20
ENTER A NUMBER:0
Exception is caught   ZeroDivisionError 
last


In [ ]:
a=int(input("ENTER A NUMBER:"))
b=int(input("ENTER A NUMBER:"))
d=[]
try:
    c=a/b 
    e=d[5]
    print(e)
    
except ZeroDivisionError:
    print("Exception is caught   ZeroDivisionError ")

print("last")    
            

In [1]:
a=int(input("ENTER A NUMBER:"))
b=int(input("ENTER A NUMBER:"))
d=[]
try:
    c=a/b 
    e=d[5]
    
except ZeroDivisionError:
    print("Exception is caught   ZeroDivisionError ")
except IndexError:
    print("Exception is caught    IndexError" )
else:
    print(c)

print("last")    
            

ENTER A NUMBER:5
ENTER A NUMBER:0
Exception is caught   ZeroDivisionError 
last


In [2]:
a=int(input("ENTER A NUMBER:"))
b=int(input("ENTER A NUMBER:"))
d=[]
try:
    c=a/b 
    e=d[5]
    
except ZeroDivisionError:
    print("Exception is caught   ZeroDivisionError ")
except IndexError:
    print("Exception is caught    IndexError" )
else:
    print(c)

print("last")    
            

ENTER A NUMBER:5
ENTER A NUMBER:5
Exception is caught    IndexError
last


In [5]:
a=int(input("ENTER A NUMBER:"))
b=int(input("ENTER A NUMBER:"))
d=[]
try:
    c=a/b 
    e=d[5]
except:
    print("Exception is caught")

    
else:
    print(c)

print("last")    
            

ENTER A NUMBER:5
ENTER A NUMBER:0
Exception is caught
last


In [6]:
print("hello")
a=int(input("ENTER A NUMBER:"))
b=int(input("ENTER A NUMBER:"))
d=[]
try:
    c=a/b 
    e=d[5] 
except ZeroDivisionError:
    print("Exception is caught   ZeroDivisionError ")
else:
    print(c)

print("last")    
            

hello
ENTER A NUMBER:5
ENTER A NUMBER:0
Exception is caught   ZeroDivisionError 
last


In [9]:
a=int(input("ENTER A NUMBER:"))
b=int(input("ENTER A NUMBER:"))
d=[]
try:
    c=a/b 
    e=d[5]
except Exception as e:
    print("Exception is caught"+"=="+str(e))

    #if there is any exception not mention in class so we have to made any except
else: #general exception will be last
    print(c)

print("last")    
            

ENTER A NUMBER:5
ENTER A NUMBER:5
Exception is caught==list index out of range
last


In [2]:
print("hello")
a=int(input("ENTER A NUMBER:"))
b=int(input("ENTER A NUMBER:"))
d=[]
try:
    c=a/b 
    e=d[5] 
except ZeroDivisionError:
    print("Exception is caught   ZeroDivisionError ")
else:
    print(c)

finally:
    print("last")    
            

hello
ENTER A NUMBER:4
ENTER A NUMBER:4
last


IndexError: list index out of range

# raising our own exception

In [4]:
#we can define our own exception

In [18]:
class student():
    def __init__(self,name,age):
        if age>80 or age<16:
            raise Exception ("Age can not be less than 16 and more than 80")
        self.name=name
        self.age=age

In [19]:
student1=student("bilal",15)

Exception: Age can not be less than 16 and more than 80

In [20]:
#here exception is raised which we want

In [21]:
try:
    st=student("bilal",15)
except Exception as e:
    print(f"exception +{str(e)}")
else:
    print("last")

exception +Age can not be less than 16 and more than 80


#  IMPORTANT

In [22]:
class student():
    def __init__(self,name,age):
        if age>80 or age<16:
            raise Exception ("Age can not be less than 16 and more than 80")
        self.name=name
        self.age=age
class StudentAgeException(Exception):
    pass

# NumPy

In [3]:
list_1=[1,2,3,4,5]
empty=[]
for i in list_1:
    empty.append(i*5)


In [4]:
empty

[5, 10, 15, 20, 25]

In [5]:
import numpy as np

In [7]:
num=np.array([1,2,3,4,5])
a=num*4
a

array([ 4,  8, 12, 16, 20])

In [8]:
 a>10

array([False, False,  True,  True,  True])

In [9]:
a1=np.array([1.0,24,543])
a1

array([  1.,  24., 543.])

In [10]:
a2=np.array([1,2,3423,65.32,2342.4432],dtype=int)
a2

array([   1,    2, 3423,   65, 2342])

In [12]:
def square(a):
    result=[]
    for i in a:
        result.append(a)
    return result

In [13]:
to_sq=range(100000)

In [14]:
%timeit  square(to_sq)

10.5 ms ± 668 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [15]:
c=np.arange(100000)

In [17]:
%timeit c**2

77.3 µs ± 4.86 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [18]:
n3=np.array([0]*10)

In [19]:
n3

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [30]:
a=np.arange(10,0,-1)
a

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [24]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [27]:
a=np.ones(5)

In [28]:
a

array([1., 1., 1., 1., 1.])

In [31]:
np.zeros_like(a)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [32]:
np.ones_like(a)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

# 2D ARRAY

In [39]:
_2d=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [40]:
_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
np.size(_2d)

9

In [42]:
len(_2d)

3

In [43]:
_2d.shape

(3, 3)

In [45]:
abc=np.arange(25).reshape(5,5)

In [46]:
abc

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [47]:
np.size(abc)

25

In [49]:
np.size(abc,0)#row

5

In [50]:
np.size(abc,1)#column

5

In [51]:
abc.reshape(25)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [2]:
import numpy as np

In [3]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [4]:
a=np.random.randn(20).reshape(5,4)#normal distribution
a

array([[-0.58080284, -0.16922632,  0.98836411,  1.22953099],
       [-0.35136453, -0.23085704, -0.38618891,  0.95784583],
       [-0.76076601,  1.85265467,  0.79380822, -0.90367671],
       [-1.37778031,  0.34919315,  0.01818485, -1.5027943 ],
       [ 0.61378016,  1.6888117 ,  1.38236784,  1.54329319]])

In [5]:
b=np.arange(20).reshape(4,5)
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [6]:
b[3,2] # first one row and second column

17

In [7]:
b[0,4]

4

In [9]:
b[1,]

array([5, 6, 7, 8, 9])

In [10]:
b[1:3,1:3]

array([[ 6,  7],
       [11, 12]])

In [12]:
b[2:3,2:3] # row into column

array([[12]])

In [17]:
b[1:3,0:]

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [18]:
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [19]:
b[:,4]

array([ 4,  9, 14, 19])

In [20]:
b[:,1]

array([ 1,  6, 11, 16])

In [30]:
b[3,]      #SAME

array([15, 16, 17, 18, 19])

In [31]:
b[3:4,0:5]  #SAME

array([[15, 16, 17, 18, 19]])

In [28]:
b[3,:]      #SAME

array([15, 16, 17, 18, 19])